import type { HistoryEntry } from '../types/dataset';

export function generatePandasScript(sourceFileName: string | undefined, history: HistoryEntry[]): string {
  const readCall = sourceFileName?.match(/\.xlsx?$/i)
    ? `pd.read_excel("${sourceFileName}")`
    : `pd.read_csv("${sourceFileName ?? 'your_file.csv'}")`;

  const lines = [
    '# Generated by Tidy — reproduces the cleaning steps performed in the app.',
    'import pandas as pd',
    '',
    `df = ${readCall}`,
    '',
  ];

  if (history.length === 0) {
    lines.push('# No cleaning steps were applied.');
  } else {
    history.forEach((h, i) => {
      lines.push(`# ${i + 1}. ${h.label}`);
      lines.push(h.code);
      lines.push('');
    });
  }

  lines.push('df.to_csv("cleaned_output.csv", index=False)');
  return lines.join('\n');
}
